FROM rnix/nginx-gost

# Uncoment if you want generate sertificates automatically
# COPY gen_demo_gost_certs.sh /
# RUN chmod +x /gen_demo_gost_certs.sh
# RUN /gen_demo_gost_certs.sh

#########################
#        RUNNUNG        #
#########################

# docker run --rm --network=gost-network -v /workdir/openssl-gost/nginx-gost/conf/:/etc/nginx/ --name gost.example.com gost-example-com