#FROM rnix/nginx-gost
FROM gosha20777/nginx-gost:dev

# Uncoment if you want generate sertificates automatically
#COPY gen_demo_gost_certs.sh /
#RUN chmod +x /gen_demo_gost_certs.sh
#RUN /gen_demo_gost_certs.sh
#COPY /conf/nginx.conf /etc/nginx/nginx.conf

COPY /conf/nginx.conf /etc/nginx/nginx.conf
COPY /conf/cert.pem /etc/nginx/cert.pem
COPY /conf/key.pem /etc/nginx/key.pem
COPY /conf/cert_gost2001.pem /etc/nginx/cert_gost2001.pem
COPY /conf/key_gost2001.pem /etc/nginx/key_gost2001.pem

#########################
#        RUNNUNG        #
#########################

# docker build -f Dockerfile_gost_example_com -t gost-example-com .
# docker run --rm -p 80:80 --name gost.example.com gost-example-com