#FROM rnix/nginx-gost
FROM nginx-gost

# Uncoment if you want generate sertificates automatically
#COPY gen_demo_gost_certs.sh /
#RUN chmod +x /gen_demo_gost_certs.sh
#RUN /gen_demo_gost_certs.sh
#COPY /conf/nginx.conf /etc/nginx/nginx.conf

COPY /conf/nginx.conf /etc/nginx/nginx.conf
COPY /conf/cert.pem /etc/nginx/cert.pem
COPY /conf/key.pem /etc/nginx/key.pem

#########################
#        RUNNUNG        #
#########################

# docker run --rm --network=gost-network -v /workdir/openssl-gost/nginx-gost/conf/:/etc/nginx/ --name gost.example.com gost-example-com